export const CAREER_HEAD = "Career Consultation"
export const MARRIAGE_HEAD = "Marriage/ Relationsip/ Kundali Matching"
export const HEALTH_HEAD = "Health Consultation"
export const EMERGENCY_HEAD = "Skip the Queue: Consult Today"
export const DIRECT_HEAD = "Direct 1 to 1 call/chat consultation"