export const CAREER_HEAD = "Career Consultation by Shweta"
export const MARRIAGE_HEAD = "Marriage/ Relationsip/ Kundali Matching Consultation by Shweta"
export const HEALTH_HEAD = "Health Consultation by Shweta"
export const EMERGENCY_HEAD = "Skip the Queue: Consult Today"
export const DIRECT_HEAD = "Direct one to one call/chat consultation with me"